[[news]]
date = "2026.05"
content = "录取为四川大学博士研究生。"

[[news]]
date = "2026.02"
content = "IEEE SMC 论文 *Quantum Group Decision Making Method With Linguistic Z-Numbers Based on Trust Network* 被 *IEEE Transactions on Systems, Man, and Cybernetics: Systems* 录用。"